### ISSUE TITLE
Issue updating date properties

### ISSUE THREAD

**Issue by frankydee69** [Enterprise-Content-Management/documentum-rest-client-dotnet#12]
Hi there,
1st, thank you for this stuff, it's a great help to get started. 
2nd, I see that this project has not been active for a while but hopefully, you can still help me a bit.

I have a .NET framework app written using your code and I have an issue when updating a Date property with a D2Document.

I get the D2Document object properties, no problem with that. It has a date attribute (approval_date).
Just for the sake of my testing, I set the property to the same value  with:
doc.SetPropertyValue("approval_date", doc.GetPropertyValue("approval_date"))

As you can see, I didn't touch the value.

when I save the document with doc.save(), I get the following error in my app's log file:

Error URI: http://documentum:8080/D2-Smartview/repositories/BTM/documents/0900269280009dc6
System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 ().
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at BTMsoftware.D2Rest.Net.RestController.Post[T,R](Int32 indentation, String uri, T requestBody, List`1 query) in C:\BTM\D2-REST\Utilities\BTMsoftware.Rest.DRAWbridge.D2.RestClient\Controller\Net\RestController.cs:line 475
Response status code does not indicate success: 400 ().
System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 ().
   at BTMsoftware.D2Rest.Net.RestController.Post[T,R](Int32 indentation, String uri, T requestBody, List`1 query) in C:\BTM\D2-REST\Utilities\BTMsoftware.Rest.DRAWbridge.D2.RestClient\Controller\Net\RestController.cs:line 491
   at BTMsoftware.D2Rest.Net.RestController.Post[T](Int32 indentation, String uri, T requestBody, List`1 query) in C:\BTM\D2-REST\Utilities\BTMsoftware.Rest.DRAWbridge.D2.RestClient\Controller\Net\RestController.cs:line 576
   at BTMsoftware.D2Rest.Net.RestController.Post[T](Int32 indentation, String uri, T requestBody) in C:\BTM\D2-REST\Utilities\BTMsoftware.Rest.DRAWbridge.D2.RestClient\Controller\Net\RestController.cs:line 563
   at BTMsoftware.D2Rest.DataModel.PersistentObject.Save(Int32 indentation) in C:\BTM\D2-REST\Utilities\BTMsoftware.Rest.DRAWbridge.D2.RestClient\DataModel\Core\PersistentObjectExec.cs:line 200
   at BTMsoftware.DRAWbridge.Smartview.Connector.Properties(String Filename, Int32 Indentation) in C:\BTM\D2-REST\Kernel\BTMsoftware.DRAWbridge.Smartview\Connector.vb:line 2807

On the app server, I don;t get any errors in the log file but at the end before returning, I see
Date	Time	Logger	Message
01/10/2024	11:11:57.983	com.emc.documentum.rest.error.RestErrorBuilder	Locale used in RestError: en
01/10/2024	11:11:57.983	com.emc.documentum.rest.error.RestErrorBuilder	LogId: 658f008c-42d8-4503-af45-4cc798c2483c, Status: 400, code: E_INPUT_MESSAGE_NOT_READABLE, message: The input message is not readable. …
01/10/2024	11:11:57.986	org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor	Using 'application/vnd.emc.documentum+json', given [application/vnd.emc.documentum+json, application/home+json, application/json] and supported [application/*+json, application/json, */*, application/*+xml, application/xml]
01/10/2024	11:11:57.986	org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor	Writing [com.emc.documentum.rest.model.RestError@3eef494b]
01/10/2024	11:11:57.986	com.emc.d2fs.dctm.web.services.D2fsConfigurationChangeListener	Inside isAlive true
01/10/2024	11:11:57.987	com.emc.documentum.rest.error.http.GeneralHandlerExceptionResolver	Resolved [com.emc.documentum.rest.parser.AnnotationParseException: Error in unmarshalling the JSON representation into annotated object of class com.emc.documentum.rest.model.DocumentObject at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 120]]
01/10/2024	11:11:57.987	com.emc.documentum.rest.servlet.RestDispatcherServlet	Completed 400 BAD_REQUEST

Would you have any idea?

**Comment by frankydee69** [comment]
I forgot to mention that I'm actually using Smartview, not D2-REST directly but since Smartview is built with D2-Rest, I wouldn't expect it to be a problem
